"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flexprice.models import errorresponse as models_errorresponse
from flexprice.models.errors import FlexpriceError
from flexprice.types import BaseModel
import httpx
from typing import Dict, Optional


class ErrorResponseData(BaseModel):
    code: Optional[models_errorresponse.Code] = None
    details: Optional[Dict[str, models_errorresponse.Details]] = None
    http_status_code: Optional[int] = None
    message: Optional[str] = None


@dataclass(unsafe_hash=True)
class ErrorResponse(FlexpriceError):
    data: ErrorResponseData = field(hash=False)

    def __init__(
        self,
        data: ErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
