"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .analyticscolumn import AnalyticsColumn, AnalyticsColumnTypedDict
from .analyticsquerymeta import AnalyticsQueryMeta, AnalyticsQueryMetaTypedDict
from flexprice.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AnalyticsQueryResultTypedDict(TypedDict):
    columns: NotRequired[List[AnalyticsColumnTypedDict]]
    meta: NotRequired[AnalyticsQueryMetaTypedDict]
    rows: NotRequired[List[List[str]]]


class AnalyticsQueryResult(BaseModel):
    columns: Optional[List[AnalyticsColumn]] = None

    meta: Optional[AnalyticsQueryMeta] = None

    rows: Optional[List[List[str]]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columns", "meta", "rows"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
