"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ChangedInvoiceTypedDict(TypedDict):
    action: NotRequired[str]
    r"""\"created\" | \"wallet_credit\" """
    id: NotRequired[str]
    status: NotRequired[str]


class ChangedInvoice(BaseModel):
    action: Optional[str] = None
    r"""\"created\" | \"wallet_credit\" """

    id: Optional[str] = None

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["action", "id", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
