"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from flexprice.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ChangedLineItemTypedDict(TypedDict):
    change_action: NotRequired[str]
    r"""\"created\" | \"updated\" | \"ended\" """
    end_date: NotRequired[datetime]
    id: NotRequired[str]
    price_id: NotRequired[str]
    quantity: NotRequired[str]
    start_date: NotRequired[datetime]


class ChangedLineItem(BaseModel):
    change_action: Optional[str] = None
    r"""\"created\" | \"updated\" | \"ended\" """

    end_date: Optional[datetime] = None

    id: Optional[str] = None

    price_id: Optional[str] = None

    quantity: Optional[str] = None

    start_date: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["change_action", "end_date", "id", "price_id", "quantity", "start_date"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
