"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clonefeaturerequest import CloneFeatureRequest, CloneFeatureRequestTypedDict
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class CloneFeatureRequestRequestTypedDict(TypedDict):
    id: str
    r"""Source Feature ID"""
    body: CloneFeatureRequestTypedDict
    r"""Clone configuration"""


class CloneFeatureRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Source Feature ID"""

    body: Annotated[
        CloneFeatureRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Clone configuration"""
