"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Dict, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


Code = Union[
    Literal[
        "not_found",
        "already_exists",
        "version_conflict",
        "validation_error",
        "invalid_operation",
        "permission_denied",
        "http_client_error",
        "database_error",
        "system_error",
        "internal_error",
        "service_unavailable",
    ],
    UnrecognizedStr,
]


class DetailsTypedDict(TypedDict):
    pass


class Details(BaseModel):
    pass


class ErrorResponseTypedDict(TypedDict):
    code: NotRequired[Code]
    details: NotRequired[Dict[str, DetailsTypedDict]]
    http_status_code: NotRequired[int]
    message: NotRequired[str]


class ErrorResponse(BaseModel):
    code: Optional[Code] = None

    details: Optional[Dict[str, Details]] = None

    http_status_code: Optional[int] = None

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["code", "details", "http_status_code", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
