"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .executesubscriptioninheritancerequest import (
    ExecuteSubscriptionInheritanceRequest,
    ExecuteSubscriptionInheritanceRequestTypedDict,
)
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ExecuteSubscriptionModifyRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: ExecuteSubscriptionInheritanceRequestTypedDict
    r"""External customer IDs to inherit"""


class ExecuteSubscriptionModifyRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        ExecuteSubscriptionInheritanceRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""External customer IDs to inherit"""
