"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .submodifyinheritancerequest import (
    SubModifyInheritanceRequest,
    SubModifyInheritanceRequestTypedDict,
)
from .submodifyquantitychangerequest import (
    SubModifyQuantityChangeRequest,
    SubModifyQuantityChangeRequestTypedDict,
)
from .subscriptionmodifytype import SubscriptionModifyType
from flexprice.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ExecuteSubscriptionModifyRequestTypedDict(TypedDict):
    type: SubscriptionModifyType
    inheritance_params: NotRequired[SubModifyInheritanceRequestTypedDict]
    quantity_change_params: NotRequired[SubModifyQuantityChangeRequestTypedDict]


class ExecuteSubscriptionModifyRequest(BaseModel):
    type: SubscriptionModifyType

    inheritance_params: Optional[SubModifyInheritanceRequest] = None

    quantity_change_params: Optional[SubModifyQuantityChangeRequest] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["inheritance_params", "quantity_change_params"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
