"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetCheckoutSessionRequestTypedDict(TypedDict):
    id: str
    r"""Checkout session ID"""


class GetCheckoutSessionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Checkout session ID"""
