"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class GetHuggingFaceBillingDataRequestTypedDict(TypedDict):
    request_ids: List[str]


class GetHuggingFaceBillingDataRequest(BaseModel):
    request_ids: Annotated[List[str], pydantic.Field(alias="requestIds")]


try:
    GetHuggingFaceBillingDataRequest.model_rebuild()
except NameError:
    pass
