"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetIntegrationRequestTypedDict(TypedDict):
    provider: str
    r"""Integration provider"""


class GetIntegrationRequest(BaseModel):
    provider: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Integration provider"""
