"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class HandlePaddleWebhookRequestTypedDict(TypedDict):
    tenant_id: str
    r"""Tenant ID"""
    environment_id: str
    r"""Environment ID"""
    paddle_signature: str
    r"""Paddle webhook signature"""


class HandlePaddleWebhookRequest(BaseModel):
    tenant_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Tenant ID"""

    environment_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Environment ID"""

    paddle_signature: Annotated[
        str,
        pydantic.Field(alias="Paddle-Signature"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Paddle webhook signature"""
