"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscriptionpauseresponse import (
    SubscriptionPauseResponse,
    SubscriptionPauseResponseTypedDict,
)
from flexprice.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListSubscriptionPausesResponseTypedDict(TypedDict):
    r"""Response object for listing subscription pauses with total count"""

    items: NotRequired[List[SubscriptionPauseResponseTypedDict]]
    r"""List of subscription pause objects
    @Description Array of subscription pauses
    """
    total: NotRequired[int]
    r"""Total number of pauses
    @Description Total count of subscription pauses in the response
    """


class ListSubscriptionPausesResponse(BaseModel):
    r"""Response object for listing subscription pauses with total count"""

    items: Optional[List[SubscriptionPauseResponse]] = None
    r"""List of subscription pause objects
    @Description Array of subscription pauses
    """

    total: Optional[int] = None
    r"""Total number of pauses
    @Description Total count of subscription pauses in the response
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["items", "total"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
