"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .aggregationtype import AggregationType
from .meterusagepoint import MeterUsagePoint, MeterUsagePointTypedDict
from flexprice.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class MeterUsageQueryResponseTypedDict(TypedDict):
    aggregation_type: NotRequired[AggregationType]
    event_count: NotRequired[int]
    meter_id: NotRequired[str]
    points: NotRequired[List[MeterUsagePointTypedDict]]
    total_value: NotRequired[str]


class MeterUsageQueryResponse(BaseModel):
    aggregation_type: Optional[AggregationType] = None

    event_count: Optional[int] = None

    meter_id: Optional[str] = None

    points: Optional[List[MeterUsagePoint]] = None

    total_value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["aggregation_type", "event_count", "meter_id", "points", "total_value"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
