"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pausesubscriptionrequest import (
    PauseSubscriptionRequest,
    PauseSubscriptionRequestTypedDict,
)
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PauseSubscriptionRequestRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: PauseSubscriptionRequestTypedDict
    r"""Pause subscription request"""


class PauseSubscriptionRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        PauseSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Pause subscription request"""
