"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cloneplanrequest import ClonePlanRequest, ClonePlanRequestTypedDict
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PostPlansIDCloneRequestTypedDict(TypedDict):
    id: str
    r"""Source Plan ID"""
    body: ClonePlanRequestTypedDict
    r"""Clone configuration"""


class PostPlansIDCloneRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Source Plan ID"""

    body: Annotated[
        ClonePlanRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Clone configuration"""
