"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resumesubscriptionrequest import (
    ResumeSubscriptionRequest,
    ResumeSubscriptionRequestTypedDict,
)
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ResumeSubscriptionRequestRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: ResumeSubscriptionRequestTypedDict
    r"""Resume subscription request"""


class ResumeSubscriptionRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        ResumeSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Resume subscription request"""
