"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .wallet import Wallet, WalletTypedDict
from .wallettransactionresponse import (
    WalletTransactionResponse,
    WalletTransactionResponseTypedDict,
)
from flexprice.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TopUpWalletResponseTypedDict(TypedDict):
    invoice_id: NotRequired[str]
    r"""Invoice ID if an invoice was created (only for PURCHASED_CREDIT_INVOICED)"""
    wallet: NotRequired[WalletTypedDict]
    wallet_transaction: NotRequired[WalletTransactionResponseTypedDict]


class TopUpWalletResponse(BaseModel):
    invoice_id: Optional[str] = None
    r"""Invoice ID if an invoice was created (only for PURCHASED_CREDIT_INVOICED)"""

    wallet: Optional[Wallet] = None

    wallet_transaction: Optional[WalletTransactionResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["invoice_id", "wallet", "wallet_transaction"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
