"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatepaymentstatusrequest import (
    UpdatePaymentStatusRequest,
    UpdatePaymentStatusRequestTypedDict,
)
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateInvoicePaymentStatusRequestTypedDict(TypedDict):
    id: str
    r"""Invoice ID"""
    body: UpdatePaymentStatusRequestTypedDict
    r"""Payment Status Update Request"""


class UpdateInvoicePaymentStatusRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Invoice ID"""

    body: Annotated[
        UpdatePaymentStatusRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Payment Status Update Request"""
