"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatepriceunitrequest import (
    UpdatePriceUnitRequest,
    UpdatePriceUnitRequestTypedDict,
)
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdatePriceUnitRequestRequestTypedDict(TypedDict):
    id: str
    r"""Price unit ID"""
    body: UpdatePriceUnitRequestTypedDict
    r"""Price unit details to update"""


class UpdatePriceUnitRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Price unit ID"""

    body: Annotated[
        UpdatePriceUnitRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Price unit details to update"""
