"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatealertsettingsrequest import (
    UpdateAlertSettingsRequest,
    UpdateAlertSettingsRequestTypedDict,
)
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateAlertSettingsRequestRequestTypedDict(TypedDict):
    id: str
    r"""Alert Settings ID"""
    body: UpdateAlertSettingsRequestTypedDict
    r"""Alert settings"""


class UpdateAlertSettingsRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Alert Settings ID"""

    body: Annotated[
        UpdateAlertSettingsRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Alert settings"""
