"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customer_1 import Customer1, Customer1TypedDict
from .feature_1 import Feature1, Feature1TypedDict
from .wallet import Wallet, WalletTypedDict
from .webhookeventname import WebhookEventName
from flexprice.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class WebhookDtoAlertWebhookPayloadTypedDict(TypedDict):
    alert_status: NotRequired[str]
    alert_type: NotRequired[str]
    customer: NotRequired[Customer1TypedDict]
    r"""Customer response object containing all customer information"""
    event_type: NotRequired[WebhookEventName]
    feature: NotRequired[Feature1TypedDict]
    wallet: NotRequired[WalletTypedDict]


class WebhookDtoAlertWebhookPayload(BaseModel):
    alert_status: Optional[str] = None

    alert_type: Optional[str] = None

    customer: Optional[Customer1] = None
    r"""Customer response object containing all customer information"""

    event_type: Optional[WebhookEventName] = None

    feature: Optional[Feature1] = None

    wallet: Optional[Wallet] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "alert_status",
                "alert_type",
                "customer",
                "event_type",
                "feature",
                "wallet",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
