"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_customerresponse import DtoCustomerResponse, DtoCustomerResponseTypedDict
from .dto_walletresponse import DtoWalletResponse, DtoWalletResponseTypedDict
from .webhookdto_walletalertinfo import (
    WebhookDtoWalletAlertInfo,
    WebhookDtoWalletAlertInfoTypedDict,
)
from .webhookeventname import WebhookEventName
from flexprice.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class WebhookDtoWalletWebhookPayloadTypedDict(TypedDict):
    alert: NotRequired[WebhookDtoWalletAlertInfoTypedDict]
    customer: NotRequired[DtoCustomerResponseTypedDict]
    r"""Customer response object containing all customer information"""
    event_type: NotRequired[WebhookEventName]
    wallet: NotRequired[DtoWalletResponseTypedDict]


class WebhookDtoWalletWebhookPayload(BaseModel):
    alert: Optional[WebhookDtoWalletAlertInfo] = None

    customer: Optional[DtoCustomerResponse] = None
    r"""Customer response object containing all customer information"""

    event_type: Optional[WebhookEventName] = None

    wallet: Optional[DtoWalletResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["alert", "customer", "event_type", "wallet"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
